### ISSUE TITLE
Variable assignment proxying upstream by default

### ISSUE THREAD

**Issue by ahamid** [kriszyp/alkali#38]
In the process of trying to exploit the behavior of "non-proxying" variable assignment for derived/dynamic defaults, as documented [here](https://github.com/kriszyp/alkali#variable-proxying), I noticed that this may not be working.

```javascript
let sourceVariable = new Variable({foo: 1})
let containingVariable = new Variable(sourceVariable)
sourceVariable.set('foo', 2) // this will propagate down to containingVariable
containingVariable.set('foo', 3) // this will not affect the sourceVariable
containingVariable.get('foo') -> 3
sourceVariable.get('foo') -> 2
```

Test cases at PR #39

**Comment by kriszyp** [comment]
Alkali did indeed have that behavior at one point, and the documentation described that. That behavior has since been removed, and the documentation hasn't been updated. But I'll try to provide more explanation.

This behavior was motivated by trying to enable semantics more similar to "persistent" languages (scala, clojure with immutable data structures that are replaced at specific variable points). However, this tends to conflict with what I believe is a more pressing and overriding goal, for intuitive use, of making alkali a "variablized" form of JS that mirrors JS semantics as closely as possible. In that latter sense, the create-new-instance-on-set semantics described in the "non-proxying derived variable" section is surprising from a JS perspective.

For example, let's consider a JS/alkali equivalence of assigning an object and setting a property:
static JS:
```
let a = {foo: 1}
let b = a
b.foo = 2
a.foo -> // expect 2
```
variabilized equivalent (basically what you have above):
```
let a = new Variable({foo: 1})
let b = new Variable(a)
b.set('foo', 2)
a.get('foo') -> // expect JS or scala response? :)
```
Anyway, I am certainly open to discussion on this, but altering the semantics of object setting seems like it would be more unexpected to JS devs than it is worth, and because we are dealing with underlying objects that aren't really persistent/immutable objects, I think it results in surprises in terms of inconsistencies with the underlying objects and how the variable suddenly points to a new object.

**Comment by ahamid** [comment]
Thanks @kriszyp, that makes sense.  I'm not necessarily lobbying for particular behavior here, but noticed this behavior could in theory solve a problem I was attempting to solve manually, which I think is more fundamental (and perhaps you have idea/guidance on): dynamic initial value.

For example, let's say you have a set of defaults or stored values that themselves are either obtained asynchronously and delivered via an alkali chain (user settings), or vary based on some other configuration.  At the same time you need to (eventually) be able to override those defaults with new values.  Dropdown/checkbox selection is a classic example:

```javascript
let dataSource = ...
let defaults = dataSource.to(d => return d.reduce((s,k,v) => s[k] = v), {}))
let selection = new Variable(defaults /* ? */)
...
// later
Checkbox({ value: selection.property('option1') })

selection.to(/*...do some things with current selection...*/)
```

An expedient (but incorrect, imho) solution is to eagerly collapse defaults to feed the selection its initial value.  This of course could potentially produce an incorrect/incomplete initial value depending on timing, and also decouples the default from any further upstream changes.

An alternative I was working on was intelligently dynamically merging the defaults with concrete selection, based on whether the selection itself had been updated yet (for example, by the user).  I think this is workable, but then I noticed the docs and it seemed like I could get this behavior for free, which was certainly more appealing :)

I also noticed the support for the Variable `.default` value, perhaps this could be exploited somehow, as long as the scenario can guarantee that the initial unmodified value of the target variable can be `undefined` (I'm not sure if invoking `.property()` itself sets an implicit value)

**Comment by ahamid** [comment]
#39 Fixed tests to reflect expected behavior. Added new tests that exercise variable default behavior, esp. wrt Property: 9855b5770f6523b6659207fde8e08319bfaedc0a
