### ISSUE TITLE
Feature request: support for Map

### ISSUE THREAD

**Issue by kvcrawford** [kriszyp/alkali#5]
Can the `property`, `get`, and `set` methods for object variables be extended to work for `Map` data structures?

```js
let selection = new Variable(new Map())

// User selects the `false` value
selection.set(false, true)

selection.get(false)
// -> true
```

**Comment by kriszyp** [comment]
So I think the way we would do this is when we get or set properties, if
the target value/ object has a `get` and `set`, we would use them instead
of direct property access within a variable. (Basically duck -typing). I
think that seems very reasonable,I will go ahead and add that.

**Comment by kriszyp** [comment]
I am not entirely sure this fix is the best way, since we are actually producing different behavior for determining what keys result in different property children variables. This fix bases this on the object type, but that could change. It might be preferable to actually have a separate constructor for this behavior, but this should work for the case of directly adding a Map on instantiation.
